// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// transformMap
DataFrame transformMap(CharacterVector argv);
RcppExport SEXP cartogramone_transformMap(SEXP argvSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type argv(argvSEXP);
    rcpp_result_gen = Rcpp::wrap(transformMap(argv));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"cartogramone_transformMap", (DL_FUNC) &cartogramone_transformMap, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_cartogramone(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
